-- Example schema matching the shipped transformer (syncdb/transformer.py).
-- Adapt or replace with your real tables; the sync engine only needs the
-- key column on the source to be indexed (a primary key is ideal).

-- Source: change log, potentially hundreds of millions of rows. Each row
-- says what happened to one order: 'I' = inserted, 'U' = updated,
-- 'D' = deleted. Delete rows typically carry only the business key
-- (ORDER_ID); the remaining columns stay NULL.
CREATE TABLE order_changes (
    change_id       NUMBER         GENERATED BY DEFAULT AS IDENTITY,
    operation       CHAR(1)        NOT NULL
                    CONSTRAINT order_changes_op_ck CHECK (operation IN ('I', 'U', 'D')),
    order_id        NUMBER         NOT NULL,
    cust_first_name VARCHAR2(100),
    cust_last_name  VARCHAR2(100),
    order_date      DATE,
    unit_price      NUMBER(12, 2),
    quantity        NUMBER(8),
    status_code     VARCHAR2(2),
    country_code    VARCHAR2(2),
    CONSTRAINT order_changes_pk PRIMARY KEY (change_id)
);

-- Target: reshaped reporting table kept in sync by applying the change log.
CREATE TABLE order_summary (
    order_id      NUMBER        NOT NULL,
    customer_name VARCHAR2(201) NOT NULL,
    order_year    NUMBER(4)     NOT NULL,
    order_month   NUMBER(2)     NOT NULL,
    total_amount  NUMBER(14, 2) NOT NULL,
    status        VARCHAR2(20)  NOT NULL,
    region        VARCHAR2(20)  NOT NULL,
    synced_at     TIMESTAMP     NOT NULL,
    CONSTRAINT order_summary_pk PRIMARY KEY (order_id)
);

-- Optional: seed a little demo data — inserts, some updates, some deletes.
-- INSERT INTO order_changes (operation, order_id, cust_first_name, cust_last_name,
--                            order_date, unit_price, quantity, status_code, country_code)
-- SELECT 'I', LEVEL, 'First' || LEVEL, 'Last' || LEVEL, SYSDATE - MOD(LEVEL, 365),
--        ROUND(DBMS_RANDOM.VALUE(1, 500), 2), TRUNC(DBMS_RANDOM.VALUE(1, 10)),
--        CASE MOD(LEVEL, 4) WHEN 0 THEN 'NW' WHEN 1 THEN 'SH'
--                           WHEN 2 THEN 'DL' ELSE 'CN' END,
--        CASE MOD(LEVEL, 5) WHEN 0 THEN 'US' WHEN 1 THEN 'GB'
--                           WHEN 2 THEN 'AE' WHEN 3 THEN 'IN' ELSE 'ZZ' END
-- FROM dual CONNECT BY LEVEL <= 100000;
--
-- -- Every 10th order later got shipped...
-- INSERT INTO order_changes (operation, order_id, cust_first_name, cust_last_name,
--                            order_date, unit_price, quantity, status_code, country_code)
-- SELECT 'U', order_id, cust_first_name, cust_last_name, order_date,
--        unit_price, quantity, 'SH', country_code
-- FROM order_changes WHERE operation = 'I' AND MOD(order_id, 10) = 0;
--
-- -- ...and every 100th was removed entirely.
-- INSERT INTO order_changes (operation, order_id)
-- SELECT DISTINCT 'D', order_id FROM order_changes WHERE MOD(order_id, 100) = 0;
-- COMMIT;
