-- Example schema matching the shipped transformer (syncdb/transformer.py).
-- Adapt or replace with your real tables; the sync engine only needs the
-- key column on the source to be indexed (a primary key is ideal).

-- Source: wide legacy table, potentially hundreds of millions of rows.
CREATE TABLE source_orders (
    order_id        NUMBER         GENERATED BY DEFAULT AS IDENTITY,
    cust_first_name VARCHAR2(100),
    cust_last_name  VARCHAR2(100),
    order_date      DATE           NOT NULL,
    unit_price      NUMBER(12, 2),
    quantity        NUMBER(8),
    status_code     VARCHAR2(2),
    country_code    VARCHAR2(2),
    CONSTRAINT source_orders_pk PRIMARY KEY (order_id)
);

-- Target: reshaped reporting table.
CREATE TABLE order_summary (
    order_id      NUMBER        NOT NULL,
    customer_name VARCHAR2(201) NOT NULL,
    order_year    NUMBER(4)     NOT NULL,
    order_month   NUMBER(2)     NOT NULL,
    total_amount  NUMBER(14, 2) NOT NULL,
    status        VARCHAR2(20)  NOT NULL,
    region        VARCHAR2(20)  NOT NULL,
    synced_at     TIMESTAMP     NOT NULL,
    CONSTRAINT order_summary_pk PRIMARY KEY (order_id)
);

-- Optional: seed a little demo data.
-- INSERT INTO source_orders (cust_first_name, cust_last_name, order_date,
--                            unit_price, quantity, status_code, country_code)
-- SELECT 'First' || LEVEL, 'Last' || LEVEL, SYSDATE - MOD(LEVEL, 365),
--        ROUND(DBMS_RANDOM.VALUE(1, 500), 2), TRUNC(DBMS_RANDOM.VALUE(1, 10)),
--        CASE MOD(LEVEL, 4) WHEN 0 THEN 'NW' WHEN 1 THEN 'SH'
--                           WHEN 2 THEN 'DL' ELSE 'CN' END,
--        CASE MOD(LEVEL, 5) WHEN 0 THEN 'US' WHEN 1 THEN 'GB'
--                           WHEN 2 THEN 'AE' WHEN 3 THEN 'IN' ELSE 'ZZ' END
-- FROM dual CONNECT BY LEVEL <= 100000;
-- COMMIT;
